language: r
r:
  - oldrel
  - release
  - devel

pandoc_version: 2.0.3

cache: packages

# Be strict when checking our package
warnings_are_errors: true

# Suggested packages needed to run tests
r_packages:
  - knitr
  - rmarkdown


addons:
  apt:
    packages:
    - jags
#   - lmodern
#   - libgsl0ldbl # GNU scientific library for MBESS
#   - libgsl0-dev # GNU scientific library for MBESS
#   - libnlopt-dev # nloptr
